version: '3.8'

services:
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - postgres-db
      - mongo-db
      - redis-cache
    container_name: ${SERVER_CONTAINER_NAME}
    env_file:
      - .env

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: ${POSTGRES_CONTAINER_NAME}

  mongo-db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    container_name: ${MONGO_CONTAINER_NAME}

  redis-cache:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    container_name: ${REDIS_CONTAINER_NAME}


volumes:
  postgres_data:
  mongo_data:
  redis_data:
